# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhoudini: '@launch_houdini'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchnukestudio: '@launch_nukestudio'
      tk-multi-launchphotoshopcc: '@launch_photoshopcc'
      tk-multi-launchillustratorcc: '@launch_illustratorcc'
      tk-multi-shotgunpanel:
        location:
          version: v1.4.3
          type: app_store
          name: tk-multi-shotgunpanel
    location:
      version: v0.5.2
      type: app_store
      name: tk-shell

  tk-desktop:
    apps:
      tk-multi-rv: '@launch_rv'
      tk-multi-shotgunpanel:
        location:
          version: v1.4.3
          type: app_store
          name: tk-multi-shotgunpanel
    collapse_rules:
    - {button_label: $app, match: Launch $app $version, menu_label: Launch $version}
    debug_logging: false
    default_group: THR3D
    hook_launch_python: default
    location:
      version: v2.3.4
      type: app_store
      name: tk-desktop
    show_recents: false
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------

#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      version: v0.1.6
      type: app_store
      name: tk-framework-adminui
  tk-framework-desktopserver_v1.x.x:
    location:
      version: v1.1.10
      type: app_store
      name: tk-framework-desktopserver
